language: python

python:
  - "2.7"
#  - "3.5"
#  - "nightly" # currently points to 3.6-dev

sudo: false

notifications:
  email: false
 
# Setup dependencies and install package
install:
  - wget http://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  - conda info -a
  - conda create -q -n travis-env python=$TRAVIS_PYTHON_VERSION numpy scipy pandas matplotlib=1.5.3 basemap=1.0.7 ephem astropy=1.3 fitsio=0.9.8 healpy=1.9.1 psycopg2 nose -c astropy -c kadrlica
  - source activate travis-env
  - python setup.py install
  - export OBZTAK_SURVEY='obztak'

# command to run tests
script: 
  - nosetests tests