name: obztak
channels:
  - conda-forge
  - kadrlica
dependencies:
  - numpy
  - scipy
  - pandas
  - pyyaml
  - matplotlib=1.5.3 
  - basemap=1.0.7 
  - ephem 
  - astropy=1.3 
  - fitsio=0.9.8 
  - healpy=1.9.1 
  - psycopg2 
  - nose
variables:
  OBZTAK_SURVEY: obztak